imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BookBookBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_3_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

assetic:
  assets:
    css:
      inputs: - '../app/Resources/public/css/*'

sensio_framework_extra:
   router:
        annotations: false
#FOS User Bundle
fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: Book\BookBundle\Entity\User
  from_email:
    address: "%mailer_user%"
    sender_name: "%mailer_user%"

#EasyAdminBundle
easy_admin:
  site_name: Reviewed!
  design:
    menu:
      - User
      - Book
      - Review
      - { label: Back to Reviewed!, route: index, icon: home }
  list:
    actions: ['show']
  entities:
    User:
      class: Book\BookBundle\Entity\User
      list:
        fields:
          - id
          - username
          - email
          - enabled
          - lastLogin
          - roles
          - reviews
      form:
        fields:
          - username
          - usernameCanonical
          - email
          - emailCanonical
          - enabled
          - password
          - roles
    Book:
      class: Book\BookBundle\Entity\Book
      form:
        fields:
          - title
          - author
          - isbn
          - summary_of_book
          - { property: 'imageFile', type: 'file'  }
      list:
        fields:
          - id
          - title
          - author
          - isbn
          - summary_of_book
          - reviews
          - isApproved
          - { property: 'image', type: 'image', base_path: '%app.path.book_images%' }
        show:
          fields:
          - id
          - title
          - author
          - isbn
          - { property: 'image', type: 'image', base_path: '%app.path.book_images%' }
          - summary_of_book
    Review:
      class: Book\BookBundle\Entity\Review
      disabled_actions: ['edit']
      form:
        fields:
          - title
          - author
          - book
          - review

#VichImageUploader Bundle
vich_uploader:
  db_driver: orm
  mappings:
    book_image:
      uri_prefix: '%app.path.book_images%'
      upload_destination: '%kernel.project_dir%/web%app.path.book_images%'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_remove: true

#KnpPaginator Bundle
knp_paginator:
  template:
    pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'