security:
  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting/request, role: IS_AUTHENTICATED_ANONYMOUSLY }
#    - { path: ^/resetting/send-email, role: IS_AUTHENTICATED_ANONYMOUSLY }
#    - { path: ^/resetting/check-email, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }
    - { path: ^/review/create, role: ROLE_USER }
    - { path: ^/review/edit, role: ROLE_USER }
    - { path: ^/review/delete, role: ROLE_USER }
    - { path: ^/profile/change-password, role: ROLE_USER }
  encoders:
    Book\BookBundle\Entity\User: bcrypt
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      logout:
        path: fos_user_security_logout
        target: fos_user_security_login
#        success_handler: app.login_success_handler
      anonymous: null
      form_login:
        provider: fos_userbundle
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        csrf_token_generator: security.csrf.token_manager
#        default_target_path: fos_user_profile_show
      remember_me: {secret: '%secret%'}
